import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import Header from '@/widgets/app-home/_ui/Header';
import Footer from '@/widgets/app-home/_ui/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create next App',
  description: 'Generated by create next app'
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
        {children}
        <Footer />
        </>
        
  );
}
